### ISSUE TITLE
Unable to convert classes into dex format.

### ISSUE THREAD

**Issue by Spyispie120** [PickleGames/SealTheDeal#63]
**Error seem to caused by multiple duplicated files when doing android build.
After fiddle around for couple minutes, I found that the problem seem to caused by "Unity Ad" and "Google Admob". When disable unity ad, the game was able to be built. So the problem is definitely lying around somewhere between the google ad and unity ad.**

**The full error log:**

```
CommandInvokationFailure: Unable to convert classes into dex format.
C:/Program Files/Java/jdk1.8.0_102\bin\java.exe -Xmx2048M -Dcom.android.sdkmanager.toolsdir="C:/Users/ducng/android-sdks\tools" -Dfile.encoding=UTF8 -jar "N:\Programming\Unity\Unity\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\sdktools.jar" -

stderr[
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/unity3d/ads/BuildConfig;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/unity3d/ads/IUnityAdsListener;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/unity3d/ads/UnityAds;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/unity3d/ads/UnityAds$1;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/unity3d/ads/UnityAds$2;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/unity3d/ads/UnityAds$FinishState;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/unity3d/ads/UnityAds$PlacementState;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/unity3d/ads/UnityAds$UnityAdsError;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/unity3d/ads/adunit/AdUnitActivity;

UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.RuntimeException: Translation has been interrupted
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:613)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:311)
	at com.android.dx.command.dexer.Main.run(Main.java:277)
	at com.android.dx.command.dexer.Main.main(Main.java:245)
	at com.android.dx.command.Main.main(Main.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at SDKMain.main(SDKMain.java:130)
Caused by: java.lang.InterruptedException: Too many errors
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:605)
	... 9 more
]
stdout[
processing archive N:\Programming\Repository\Seals 2017\Seals\Temp\StagingArea\android-libraries\play-services-ads-11.0.2\libs\.\classes.jar...
ignored resource META-INF/
ignored resource META-INF/MANIFEST.MF
ignored resource com/
ignored resource com/google/
ignored resource com/google/android/
ignored resource com/google/android/gms/
ignored resource com/google/android/gms/ads/
ignored resource com/google/android/gms/ads/internal/
processing com/google/android/gms/ads/internal/ClientApi.class...
ignored resource com/google/android/gms/ads/internal/js/
processing com/google/android/gms/ads/internal/js/JavascriptEngineFactory.class...
processing com/google/android/gms/ads/internal/js/JavascriptEngineFactory$JSEngineSettableFuture.class...
processing com/google/android/gms/ads/internal/js/zza.class...
processing com/google/android/gms/ads/internal/js/zzaa.class...
processing com/google/android/gms/ads/internal/js/zzab.class...
processing com/google/android/gms/ads/internal/js/zzac.class...
processing com/google/android/gms/ads/internal/js/zzad.class...
processing com/google/android/gms/ads/internal/js/zzae.class...
processing com/google/android/gms/ads/internal/js/zzaf.class...
processing com/google/android/gms/ads/internal/js/zzag.class...
processing com/google/android/gms/ads/internal/js/zzah.class...
processing com/google/android/gms/ads/internal/js/zzai.class...
processing com/google/android/gms/ads/internal/js/zzaj.class...
processing com/google/android/gms/ads/internal/js/zzak.class...
processing com/google/android/gms/ads/internal/js/zzb.class...
processing com/google/android/gms/ads/internal/js/zzc.class...
processing com/google/android/gms/ads/internal/js/zzd.class...
processing com/google/android/gms/ads/internal/js/zze.class...
processing com/google/android/gms/ads/internal/js/zzf.class...
processing com/google/android/gms/ads/internal/js/zzg.class...
processing com/google/android/gms/ads/internal/js/zzh.class...
processing com/google/android/gms/ads/internal/js/zzi.class...
processing com/google/android/gms/ads/internal/js/zzj.class...
processing com/google/android/gms/ads/internal/js/zzk.class...
processing com/google/android/gms/ads/internal/js/zzl.class...
processing com/google/android/gms/ads/internal/js/zzm.class...
processing com/google/android/gms/ads/internal/js/zzn.class...
processing com/google/android/gms/ads/internal/js/zzo.class...
processing com/google/android/gms/ads/internal/js/zzp.class...
processing com/google/android/gms/ads/internal/js/zzq.class...
processing com/google/android/gms/ads/internal/js/zzr.class...
processing com/google/android/gms/ads/internal/js/zzs.class...
processing com/google/android/gms/ads/internal/js/zzt.class...
processing com/google/android/gms/ads/internal/js/zzu.class...
processing com/google/android/gms/ads/internal/js/zzv.class...
processing com/google/android/gms/ads/internal/js/zzw.class...
processing com/google/android/gms/ads/internal/js/zzx.class...
processing com/google/android/gms/ads/internal/js/zzy.class...
processing com/google/android/gms/ads/internal/js/zzz.class...
ignored resource com/google/android/gms/ads/internal/overlay/
processing com/google/android/gms/ads/internal/overlay/AdOverlayInfoParcel.class...
processing com/google/android/gms/ads/internal/overlay/zza.class...
processing com/google/android/gms/ads/internal/overlay/zzaa.class...
processing com/google/android/gms/ads/internal/overlay/zzab.class...
processing com/google/android/gms/ads/internal/overlay/zzac.class...
processing com/google/android/gms/ads/internal/overlay/zzad.class...
processing com/google/android/gms/ads/internal/overlay/zzae.class...
processing com/google/android/gms/ads/internal/overlay/zzaf.class...
processing com/google/android/gms/ads/internal/overlay/zzag.class...
processing com/google/android/gms/ads/internal/overlay/zzaj.class...
processing com/google/android/gms/ads/internal/overlay/zzak.class...
processing com/google/android/gms/ads/internal/overlay/zzal.class...
processing com/google/android/gms/ads/internal/overlay/zzam.class...
processing com/google/android/gms/ads/internal/overlay/zzan.class...
processing com/google/android/gms/ads/internal/overlay/zzao.class...
processing com/google/android/gms/ads/internal/overlay/zzap.class...
processing com/google/android/gms/ads/internal/overlay/zzaq.class...
processing com/google/android/gms/ads/internal/overlay/zzar.class...
processing com/google/android/gms/ads/internal/overlay/zzas.class...
processing com/google/android/gms/ads/internal/overlay/zzat.class...
processing com/google/android/gms/ads/internal/overlay/zzau.class...
processing com/google/android/gms/ads/internal/overlay/zzb.class...
processing com/google/android/gms/ads/internal/overlay/zzc.class...
processing com/google/android/gms/ads/internal/overlay/zzd.class...
processing com/google/android/gms/ads/internal/overlay/zze.class...
processing com/google/android/gms/ads/internal/overlay/zzf.class...
processing com/google/android/gms/ads/internal/overlay/zzg.class...
processing com/google/android/gms/ads/internal/overlay/zzh.class...
processing com/google/android/gms/ads/internal/overlay/zzi.class...
processing com/google/android/gms/ads/internal/overlay/zzj.class...
processing com/google/android/gms/ads/internal/overlay/zzk.class...
processing com/google/android/gms/ads/internal/overlay/zzl.class...
processing com/google/android/gms/ads/internal/overlay/zzm.class...
processing com/google/android/gms/ads/internal/overlay/zzn.class...
processing com/google/android/gms/ads/internal/overlay/zzo.class...
processing com/google/android/gms/ads/internal/overlay/zzp.class...
processing com/google/android/gms/ads/internal/overlay/zzq.class...
processing com/google/android/gms/ads/internal/overlay/zzr.class...
processing com/google/android/gms/ads/internal/overlay/zzs.class...
processing com/google/android/gms/ads/internal/overlay/zzt.class...
processing com/google/android/gms/ads/internal/overlay/zzu.class...
processing com/google/android/gms/ads/internal/overlay/zzv.class...
processing com/google/android/gms/ads/internal/overlay/zzw.class...
processing com/google/android/gms/ads/internal/overlay/zzx.class...
processing com/google/android/gms/ads/internal/overlay/zzy.class...
processing com/google/android/gms/ads/internal/overlay/zzz.class...
processing com/google/android/gms/ads/internal/zza.class...
processing com/google/android/gms/ads/internal/zzaa.class...
processing com/google/android/gms/ads/internal/zzab.class...
processing com/google/android/gms/ads/internal/zzac.class...
processing com/google/android/gms/ads/internal/zzad.class...
processing com/google/android/gms/ads/internal/zzae.class...
processing com/google/android/gms/ads/internal/zzaf.class...
processing com/google/android/gms/ads/internal/zzag.class...
processing com/google/android/gms/ads/internal/zzah.class...
processing com/google/android/gms/ads/internal/zzai.class...
processing com/google/android/gms/ads/internal/zzaj.class...
processing com/google/android/gms/ads/internal/zzak.class...
processing com/google/android/gms/ads/internal/zzal.class...
processing com/google/android/gms/ads/internal/zzam.class...
processing com/google/android/gms/ads/internal/zzan.class...
processing com/google/android/gms/ads/internal/zzao.class...
processing com/google/android/gms/ads/internal/zzap.class...
processing com/google/android/gms/ads/internal/zzaq.class...
processing com/google/android/gms/ads/internal/zzar.class...
processing com/google/android/gms/ads/internal/zzas.class...
processing com/google/android/gms/ads/internal/zzat.class...
processing com/google/android/gms/ads/internal/zzau.class...
processing com/google/android/gms/ads/internal/zzav.class...
processing com/google/android/gms/ads/internal/zzaw.class...
processing com/google/android/gms/ads/internal/zzax.class...
processing com/google/android/gms/ads/internal/zzay.class...
processing com/google/android/gms/ads/internal/zzaz.class...
processing com/google/android/gms/ads/internal/zzb.class...
processing com/google/android/gms/ads/internal/zzba.class...
processing com/google/android/gms/ads/internal/zzbb.class...
processing com/google/android/gms/ads/internal/zzbc.class...
processing com/google/android/gms/ads/internal/zzbd.class...
processing com/google/android/gms/ads/internal/zzbe.class...
processing com/google/android/gms/ads/internal/zzbf.class...
processing com/google/android/gms/ads/internal/zzbg.class...
processing com/google/android/gms/ads/internal/zzbh.class...
processing com/google/android/gms/ads/internal/zzbi.class...
processing com/google/android/gms/ads/internal/zzbj.class...
processing com/google/android/gms/ads/internal/zzbk.class...
processing com/google/android/gms/ads/internal/zzbl.class...
processing com/google/android/gms/ads/internal/zzbm.class...
processing com/google/android/gms/ads/internal/zzbn.class...
processing com/google/android/gms/ads/internal/zzbo.class...
processing com/google/android/gms/ads/internal/zzbp.class...
processing com/google/android/gms/ads/internal/zzbq.class...
processing com/google/android/gms/ads/internal/zzbr.class...
processing com/google/android/gms/ads/internal/zzbs.class...
processing com/google/android/gms/ads/internal/zzbt.class...
processing com/google/android/gms/ads/internal/zzbu.class...
processing com/google/android/gms/ads/internal/zzc.class...
processing com/google/android/gms/ads/internal/zzd.class...
processing com/google/android/gms/ads/internal/zze.class...
processing com/google/android/gms/ads/internal/zzf.class...
processing com/google/android/gms/ads/internal/zzg.class...
processing com/google/android/gms/ads/internal/zzh.class...
processing com/google/android/gms/ads/internal/zzi.class...
processing com/google/android/gms/ads/internal/zzj.class...
processing com/google/android/gms/ads/internal/zzk.class...
processing com/google/android/gms/ads/internal/zzl.class...
processing com/google/android/gms/ads/internal/zzm.class...
processing com/google/android/gms/ads/internal/zzn.class...
processing com/google/android/gms/ads/internal/zzo.class...
processing com/google/android/gms/ads/internal/zzp.class...
processing com/google/android/gms/ads/internal/zzq.class...
processing com/google/android/gms/ads/internal/zzr.class...
processing com/google/android/gms/ads/internal/zzs.class...
processing com/google/android/gms/ads/internal/zzt.class...
processing com/google/android/gms/ads/internal/zzu.class...
processing com/google/android/gms/ads/internal/zzv.class...
processing com/google/android/gms/ads/internal/zzw.class...
processing com/google/android/gms/ads/internal/zzx.class...
processing com/google/android/gms/ads/internal/zzy.class...
processing com/google/android/gms/ads/internal/zzz.class...
ignored resource com/google/android/gms/dynamite/
ignored resource com/google/android/gms/dynamite/descriptors/
ignored resource com/google/android/gms/dynamite/descriptors/com/
ignored resource com/google/android/gms/dynamite/descriptors/com/google/
ignored resource com/google/android/gms/dynamite/descriptors/com/google/android/
ignored resource com/google/android/gms/dynamite/descriptors/com/google/android/gms/
ignored resource com/google/android/gms/dynamite/descriptors/com/google/android/gms/ads/
ignored resource com/google/android/gms/dynamite/descriptors/com/google/android/gms/ads/dynamite/
processing com/google/android/gms/dynamite/descriptors/com/google/android/gms/ads/dynamite/ModuleDescriptor.class...
ignored resource com/google/android/gms/internal/
processing com/google/android/gms/internal/acg.class...
processing com/google/android/gms/internal/adt.class...
processing com/google/android/gms/internal/adu.class...
processing com/google/android/gms/internal/adv.class...
processing com/google/android/gms/internal/adw.class...
processing com/google/android/gms/internal/adx.class...
processing com/google/android/gms/internal/ady.class...
processing com/google/android/gms/internal/adz.class...
processing com/google/android/gms/internal/aea.class...
processing com/google/android/gms/internal/aeb.class...
processing com/google/android/gms/internal/aec.class...
processing com/google/android/gms/internal/aeo.class...
processing com/google/android/gms/internal/aep.class...
processing com/google/android/gms/internal/aeq.class...
processing com/google/android/gms/internal/zzaaa.class...
processing com/google/android/gms/internal/zzaab.class...
processing com/google/android/gms/internal/zzaac.class...
processing com/google/android/gms/internal/zzaad.class...
processing com/google/android/gms/internal/zzaae.class...
processing com/google/android/gms/internal/zzaaf.class...
processing com/google/android/gms/internal/zzaag.class...
processing com/google/android/gms/internal/zzaah.class...
processing com/google/android/gms/internal/zzaai.class...
processing com/google/android/gms/internal/zzaaj.class...
processing com/google/android/gms/internal/zzaak.class...
processing com/google/android/gms/internal/zzaal.class...
processing com/google/android/gms/internal/zzaam.class...
processing com/google/android/gms/internal/zzaan.class...
processing com/google/android/gms/internal/zzaao.class...
processing com/google/android/gms/internal/zzaap.class...
processing com/google/android/gms/internal/zzaaq.class...
processing com/google/android/gms/internal/zzaar.class...
processing com/google/android/gms/internal/zzaas.class...
processing com/google/android/gms/internal/zzaat.class...
processing com/google/android/gms/internal/zzaau.class...
processing com/google/android/gms/internal/zzaav.class...
processing com/google/android/gms/internal/zzaaw.class...
processing com/google/android/gms/internal/zzaax.class...
processing com/google/android/gms/internal/zzaay.class...
processing com/google/android/gms/internal/zzaaz.class...
processing com/google/android/gms/internal/zzaba.class...
processing com/google/android/gms/internal/zzabb.class...
processing com/google/android/gms/internal/zzabc.class...
processing com/google/android/gms/internal/zzabd.class...
processing com/google/android/gms/internal/zza<message truncated>
```

**Comment by Spyispie120** [comment]
Fixed.
Delete these two files seem to fixed the problem.
unity-adapter-2.1.0.0.aar
unity-ads-sdk-2.1.aar
